version: '3.3'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
     - DEFAULT_REGION=ap-southeast-3
     - SERVICES=s3,lambda
     - DEBUG=${DEBUG-}
     - PERSISTENCE=${PERSISTENCE-}
     - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
    ports:
     - "127.0.0.1:4566:4566"
     - "127.0.0.1:4510-4559:4510-4559"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always